### ISSUE TITLE
Same file config overrides

### ISSUE THREAD

**Issue by lsnape** [sonian/carica#20]
I am in the process of moving our team's Clojure config management from environ over to carica. We're almost there, but one feature in particular is lacking and it would be great if it could be supported:

In most of our projects it is quite common that we override env vars when running our integration/acceptance tests. The way we do this with environ is by exporting the variables in a shell script before running the tests.

Rather than have a separate configuration file for each 'mode', it would be great if carica supported merging config maps from within the same file, much like [nomad's environments](https://github.com/jarohen/nomad).

```
{:foo 1
 :carica/environments {"integration" {:foo 2}}}
```

Where `:foo` is `2` when `CARICA_ENV` env var is `integration`.

I would expect that this merging would happen after each file config merge has been performed, so environment overrides take precedence. Of course, this does leave the situation open whereby there are, for example, multiple `integration` overrides in different files, which should follow the existing merge order.

Happy to implement this and/or something similar which allows for the same overriding behaviour :)

**Comment by leathekd** [comment]
Hi, thanks for the idea.  You can actually accomplish this with Carica's middleware.  Let me know if something like the following makes sense and meets your needs (I tinkered with this in the repl but haven't tested extensively.):

```clojure
(ns my-config
  (:require [carica.core :as carica]))

(defn env-override
  "Allow the CARICA_ENV env variable to allow appropriately named
  sub-maps to override config.  That is, if CARICA_ENV is set to
  'prod', and the config file contains a map like:

  {:some :other
   :values :here
   :retries 1
   :prod {:retries 5}}

  Then the resulting config map will look like the following after it
  passes through this middleware:

  {:some :awesome
   :values :here
   :retries 5
   :prod {:some :awesome :retries 5}}"
  [f]
  (fn [resources]
    (let [cfg-map (f resources)
          env (System/getenv "CARICA_ENV")
          env-cfg (get cfg-map (keyword env))]
      ;; maybe some logging or even an exception would be useful to
      ;; avoid wondering why you aren't seeing the config you expect
      ;; if the ENV isn't setup correctly
      (if (and env (map? env-cfg))
        (merge cfg-map env-cfg)
        cfg-map))))

;; now make a custom config function that you'll use in your code
(def config (carica/configurer (concat (carica/resources "config.json")
                                       (carica/resources "config.edn")
                                       (carica/resources "config.clj"))
                               ;; also see if you want
                               ;; carica/eval-config and/or
                               ;; carica/cache-config
                               [env-override]))

;; you might want this as well, and it's confusing during tests if you
;; accidentally use a custom config function but forget to use a
;; custom override-config
(def override-config (carica/overrider config))

;; then, elsewhere
(comment
  ;; this should now behave differently based on the value of the
  ;; CARICA_ENV env variable
  (my-config/config :retries))
```

**Comment by lsnape** [comment]
Ah that's a nice way of doing it. Thanks!

I see there's already a couple of middleware functions in the core namespace. Is this environment override middleware implemented as above something you think should be added to carica core as well?

**Comment by leathekd** [comment]
Yeah, I think it's worth adding to Carica.  My tentative plan is to put this new middleware and the existing middleware into a new namespace (```carica.middleware``` seems reasonable) while adding a few ```def```s in ```carica.core``` to maintain backwards compatibility.

I'll see if I can squeeze that and a Carica release into this week sometime (free-time willing).

**Comment by lsnape** [comment]
Sounds good to me!

I've already sketched out the env override middleware in my own branch: https://github.com/lsnape/carica/blob/env-middleware/src/carica/core.clj#L168

Will add some tests etc., plus not attached to any naming conventions (`CARICA_ENV`, `:carica-env` special keyword) so let me know if you have any preference etc.

Let me know if there's anything I can do :)
