### ISSUE TITLE
Read config files after compile to uberjar?

### ISSUE THREAD

**Issue by kwladyka** [sonian/carica#23]
Hi,

Is it possible to load configuration file after compile to uberjar? As i see it works only with resources folder, but after compile to uberjar i can't change it. My purpose is to let user set configuration like SMTP authorization etc. and use it with uberjar.

**Comment by leathekd** [comment]
Carica looks up config files on the classpath, but yeah, that appears to be nailed down in an uberjar.  Or, at least my attempts at manipulating the classpath for Carica via the command line didn't work.  I could be doing it wrong, though.

Another option would be to take the alternate config file as an argument.  I threw something together over here as an example: https://github.com/leathekd/carica-uberjar

Another option would be to specify locations on disk (e.g., /etc/some_config.edn) where you expect the config file to be inside the call to ```configurer```, here: https://github.com/leathekd/carica-uberjar/blob/master/src/carica_uberjar/core.clj#L8

Let me know if that works out for you.

**Comment by kwladyka** [comment]
Finally i used ```(read-string (slurp "./data/config.edn"))``` and it works for my purpose.

**Comment by leathekd** [comment]
Closing this as it sounds like you're all set.  Feel free to reopen if I've misunderstood.
